### ISSUE TITLE
rt kernel needed?

### ISSUE THREAD

**Issue by Pippin1st** [robbert-vdh/dotfiles#2]
Hi,

Do I need a rt kernel with these config files?

Thanks.

**Comment by robbert-vdh** [comment]
You don't, in most cases you probably won't want an RT-kernel.

For pro audio kernel wise a kernel with the PREEMPT patch set enabled is enough as a start. Or if you're on Arch, the Zen kernel is is a good choice.

**Comment by Pippin1st** [comment]
I'm on Manjaro and want to try using a laptop as an effects rack (on channel inserts, analogue mixer) for a tape artists/singing DJ's.

Last week installed Manjaro and switched to pipewire.
Next is wireplumber, carla for the effects.

Have to lookup about the PREEMPT thing :)
